# 🤖 Dependabot Configuration - org-automation
# Configuração para atualização automática e segura de dependências

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "arturdr"
    assignees:
      - "arturdr"
    labels:
      - "dependencies"
      - "python"
      - "automated"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Agrupar atualizações menores
    groups:
      dev-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"
    # Configurações de segurança
    open-pull-requests-limit: 5
    target-branch: "main"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" 
      day: "tuesday"
      time: "10:00"
    reviewers:
      - "arturdr"
    assignees:
      - "arturdr"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 3

  # Docker (se houver Dockerfiles)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday" 
      time: "11:00"
    reviewers:
      - "arturdr"
    assignees:
      - "arturdr"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 2