# Configuração de proteção de branches para a organização arturdr-org
# Este arquivo define as regras de proteção que devem ser aplicadas automaticamente

branch_protection:
  # Configurações para o branch principal (main)
  main:
    # Require pull request reviews before merging
    required_status_checks:
      strict: true
      contexts:
        - "ci-basic-workflow" # workflow básico de CI
        - "yamllint" # validação de YAML
    
    # Proteções de Pull Request
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
      required_approving_review_count: 1
      require_last_push_approval: false
    
    # Outras proteções
    enforce_admins: false
    allow_force_pushes: false
    allow_deletions: false
    block_creations: false
    required_linear_history: true
    allow_fork_syncing: true
    
    # Permitir bypass para certas pessoas/teams (opcional)
    restrictions:
      users: []
      teams: []
      apps: []

  # Configurações para branches de desenvolvimento (dev, develop, staging)
  develop:
    required_status_checks:
      strict: false
      contexts:
        - "ci-basic-workflow"
    
    required_pull_request_reviews:
      dismiss_stale_reviews: false
      require_code_owner_reviews: false
      required_approving_review_count: 1
    
    enforce_admins: false
    allow_force_pushes: true
    allow_deletions: false
    required_linear_history: false

# Padrões de branches que devem ser protegidos automaticamente
auto_protect_patterns:
  - "main"
  - "master" 
  - "develop"
  - "dev"
  - "staging"
  - "production"
  - "release/*"
  - "hotfix/*"