# Labels padrão da organização arturdr-org
# Este arquivo define todas as labels que devem ser aplicadas automaticamente
# em todos os repositórios da organização.

default_labels:
  # Labels básicas do GitHub
  - name: "bug"
    color: "d73a4a"
    description: "Algo não está funcionando"

  - name: "enhancement"
    color: "a2eeef"
    description: "Nova funcionalidade ou solicitação"

  - name: "documentation"
    color: "0075ca"
    description: "Melhorias ou adições à documentação"

  - name: "good first issue"
    color: "7057ff"
    description: "Boa primeira contribuição para novos colaboradores"

  - name: "help wanted"
    color: "008672"
    description: "Ajuda extra é necessária"

# Labels personalizadas da organização
org_labels:
  # Automação
  - name: "automation"
    color: "5319e7"
    description: "Adicionado pela automação da organização"

  # Prioridade
  - name: "priority:critical"
    color: "b60205"
    description: "Prioridade crítica - precisa ser resolvido imediatamente"

  - name: "priority:high"
    color: "d93f0b"
    description: "Alta prioridade"

  - name: "priority:medium"
    color: "fbca04"
    description: "Prioridade média"

  - name: "priority:low"
    color: "0e8a16"
    description: "Baixa prioridade"

  # Áreas/Domínios específicos da org
  - name: "area:automation"
    color: "1d76db"
    description: "Relacionado a automação e workflows"

  - name: "area:photo-processing"
    color: "0e8a16"
    description: "Processamento de fotos e imagens"

  - name: "area:raw-workflow"
    color: "5319e7"
    description: "Fluxo de trabalho RAW"

  - name: "area:metadata"
    color: "f9d0c4"
    description: "Metadados e informações EXIF"

  - name: "area:gimp"
    color: "1d76db"
    description: "Relacionado ao GIMP"

  # Status
  - name: "status:in-progress"
    color: "fbca04"
    description: "Trabalho em progresso"

  - name: "status:blocked"
    color: "d93f0b"
    description: "Bloqueado por dependências externas"

  - name: "status:on-hold"
    color: "ffffff"
    description: "Em espera temporária"

  # Tipos
  - name: "type:feature"
    color: "84b6eb"
    description: "Nova funcionalidade"

  - name: "type:bugfix"
    color: "d73a4a"
    description: "Correção de bug"

  - name: "type:maintenance"
    color: "fef2c0"
    description: "Manutenção e limpeza de código"

  - name: "type:security"
    color: "b60205"
    description: "Relacionado à segurança"