name: Run Org Automation Script
on:
  schedule:
    - cron: '0 0 * * *'  # executa diariamente à meia-noite UTC
  workflow_dispatch: {}

jobs:
  automate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      metadata: read
      # O token padrão não tem admin:org; usaremos ORG_AUTOMATION_PAT (PAT) via secrets
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run automation
        env:
          ORG_NAME: arturdrr-org
          ORG_AUTOMATION_PAT: ${{ secrets.ORG_AUTOMATION_PAT }}
        run: |
          python automa_org.py
